accounts/urls.py
from django.conf.urls import *
from django.contrib.auth.views import login, logout

urlpatterns = patterns(
    '',
    url(r'^login/$', login, {'template_name':'accounts/login.html'},name='login'), 
    url(r'^logout/$', logout, {'next_page':'/list'},name='logout'), 
    url(r'^register/$', 'accounts.views.registration',name='register'), 
)

firstproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from notes import views


from django.views.generic import ListView, DetailView
from notes.models import Note

from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', views.Landing.as_view(), name="landing"),
    url(r'^add/$', views.MyView.as_view(), name="note_add"),
    url(r'^list/(?P<folder>.*)$', views.NoteList.as_view(), name='note_list'),
    url(r'^note/(?P<pk>\d+)/edit/$', views.NoteUpdate.as_view(),  name='note_update'),
    url(r'^note/(?P<pk>\d+)/delete/$', views.NoteDelete.as_view(),  name='note_delete'),
    url(r'^note/(?P<pk>\d+)$', views.NoteDetail.as_view(),  name='detail'),
    url(r'^tag/(?P<tags>.*)$', views.NoteByGames.as_view(), name='note_listtag'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
) 

notes/models.py
from django.db import models
from django.core.urlresolvers import reverse
from accounts.models import UserProfile

# Create your models here.
class Note(models.Model):
    user = models.ForeignKey(UserProfile, blank=True, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True) #not a required field
    join_date = models.DateTimeField(null=True, blank=True) #due datetime is optional
    created = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    Achievements = models.CharField(max_length=255,null = True, blank=True)
    #folder is optional
    Sponsor= models.ForeignKey('Sponsor', related_name= "notes", null=True, blank=True)
    Games = models.ManyToManyField('Games', related_name='notes', null=True, blank=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("detail", kwargs={"pk":self.pk})
        

class Folder(models.Model):
    title = models.CharField(max_length=255)
    
    def __str__(self):
        return self.title
        
class Tag(models.Model):
    title = models.CharField(max_length=255)
    
    
    def __str__(self):
        return self.title
        
class Sponsor(models.Model):
    title = models.CharField(max_length=255)
    
    def __str__(self):
        return self.title
    
class Games(models.Model):
    title = models.CharField(max_length=255)
    
    def __str__(self):
        return self.title

notes/forms.py
from django import forms
from .models import Note, Games, Sponsor
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Hidden, Button, HTML, Div, Field, Row, Fieldset

class NoteForm(forms.ModelForm):
    class Meta: 
        model = Note
        fields = ('title','content','join_date','Achievements','Games', 'Sponsor')
        
    
    def __init__(self, *args, **kwargs):
        super(NoteForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "noteform"
        tag = Div('tag',css_class = "col-xs-12", style="padding:0px;")
        self.helper.layout.insert(5,Fieldset("Select Sponsor",Sponsor, Button("createSponsormodal", value="Add a Sponsor", css_class="btn btn-primary btn-sm col-xs-12 ", data_toggle="modal", data_target="#myModal")))
        self.helper.layout.insert(4, Fieldset("Select Games",Games, Button("createGamesmodal", value="Add a Game", css_class="btn btn-primary btn-sm col-xs-12", data_toggle="modal", data_target="#myModal")))
        self.helper.layout.append(Button('btn_createnote', 'Add Player', css_class='createnote', style="margin-top:15px;"))
        self.helper.layout.append(Hidden(name='btn_createnote', value="btn_createnote"))
        
        
        # self.helper.layout.pop(9)
        #self.helper.layout.append(Hidden(name="user", value="4"))
        #self.helper.add_input(Submit('submit', 'Create Note'))
        
    def full_clean(self):#http://stackoverflow.com/questions/4340287/override-data-validation-on-one-django-form-element
        super(NoteForm, self).full_clean()
        if 'Games' in self._errors:
            self.cleaned_data['Games'] = []
            print("remove Games errors")
            del self._errors['Games']
            
class NoteFormUpdate(forms.ModelForm):
    class Meta: 
        model = Note
        #fields = '__all__'
        exclude = ['user']
        
    def __init__(self, *args, **kwargs):
        super(NoteFormUpdate, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "noteformupdate"
        
        self.helper.add_input(Submit('submit', 'Update'))

        
class SponsorForm(forms.ModelForm):
    class Meta:
        model = Sponsor
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super(SponsorForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "Sponsorform"
        self.helper.layout.append(Hidden(name='btn_createSponsor', value="btn_createSponsor"))
        self.helper.layout.append(Button('btn_createSponsor', 'Add a Sponsor', css_class='createSponsor', data_dismiss="modal"))
        

class GamesForm(forms.ModelForm):
    class Meta:
        model = Games
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super(GamesForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "Gamesform"
        self.helper.layout.append(Hidden(name='btn_createGames', value="btn_createGames"))
        self.helper.layout.append(Button('btn_createGames', 'Add a Game', css_class='createGames', data_dismiss="modal"))
        

notes/views.py
import re
import json
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Q
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404, redirect
from .forms import NoteForm, SponsorForm, GamesForm, NoteFormUpdate
from .models import Note, Sponsor, Games
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.core.serializers.json import DjangoJSONEncoder
from accounts.models import UserProfile
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class NoteList(ListView): 
    model = Note
    queryset = Note.objects.all()

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NoteList, self).dispatch(*args, **kwargs)
    
    def get_queryset(self):
        #self.request.user will contain the "User" object, however,
        #user field in the Note model is an instance of "UserProfile" object
        #So need to ensure that when we filter all the user owned notes, we
        #filter using the 'correct' UserProfile instance based on logged in "User" object 
        #in self.request.user
        curruser = UserProfile.objects.get(user=self.request.user)
        folder = self.kwargs['folder']
        if folder == '':
            #filter based on current logged in user
            self.queryset = Note.objects.filter(user=curruser)
            return self.queryset
        else:
            #filter based on current logged in user
            self.queryset = Note.objects.all().filter(user=curruser).filter(folder__title__iexact=folder)
            return self.queryset
    
    
    def get_context_data(self, **kwargs):
        context = super(NoteList, self).get_context_data(**kwargs)
        context['total'] = self.queryset.count()
        #provided so that the avatar can be displayed in base.html
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context

class NoteDetail(DetailView):
    model = Note
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NoteDetail, self).dispatch(*args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(NoteDetail, self).get_context_data(**kwargs)
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context

class NoteUpdate(UpdateView):
    model = Note
    form_class = NoteFormUpdate
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NoteUpdate, self).dispatch(*args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(NoteUpdate, self).get_context_data(**kwargs)
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context
    
class NoteByGames(ListView):
    model = Note
    
    queryset = Note.objects.all()
    def get_queryset(self):
        Gamess = self.kwargs['Games']
        pieces = Gamess.split('/') #extract different Gamess separated by /
        
        queries = [Q(Games__title__iexact=value) for value in pieces]
        # Take one Q object from the list
        query = queries.pop()
        # Or the Q object with the ones remaining in the list
        for item in queries:
            query |= item
        # Query the model
        curruser = UserProfile.objects.filter(user=self.request.user) #only query notes by curruser
        allnotes = Note.objects.filter(user=curruser).filter(query).distinct().order_by('Games__title')
        self.queryset = allnotes #Setting the queryset to allow get_context_data to apply count
        return allnotes
    
    def get_context_data(self, **kwargs):
        context = super(NoteByGames, self).get_context_data(**kwargs)
        context['total'] = self.queryset.count()
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context


class MyView(TemplateView):
    Sponsor_form_class = SponsorForm
    Games_form_class = GamesForm
    note_form_class = NoteForm
    template_name = "notes/note_hybrid.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MyView, self).dispatch(*args, **kwargs)
        
    def get(self, request, *args, **kwargs):
        kwargs.setdefault("createSponsor_form", self.Sponsor_form_class())
        kwargs.setdefault("createGames_form", self.Games_form_class())
        kwargs.setdefault("createnote_form", self.note_form_class())
        kwargs.setdefault('curruser', UserProfile.objects.get(user=self.request.user))
        return super(MyView, self).get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        form_args = {
            'data': self.request.POST,
        }
        
        if "btn_createSponsor" in request.POST['form']:
            form = self.Sponsor_form_class(**form_args)
            if not form.is_valid():
                return self.get(request,
                                   createSponsor_form=form)
            else:
                form.save()
                data = Folder.objects.all()
                result_list = list(data.values('id','title'))
                return HttpResponse(json.dumps(result_list, cls=DjangoJSONEncoder))
        elif "btn_createGames" in request.POST['form']:
            form = self.Games_form_class(**form_args)
            if not form.is_valid():
                return self.get(request,
                                   createGames_form=form)
            else:
                form.save() #save the new object
                data = Games.objects.all() # retrieve all records
                result_list = list(data.values('id','title'))
                return HttpResponse(json.dumps(result_list, cls=DjangoJSONEncoder)) #return to ajax as success with all the new records.
        elif "btn_createnote" in request.POST['form']:
            form = self.note_form_class(**form_args)
            if not form.is_valid():
                return self.get(request,
                                   createnote_form=form) 
            else:
                try:
                    #Find out which user is logged in and get the correct UserProfile record.
                    curruser = UserProfile.objects.get(user=self.request.user)
                    obj = form.save(commit=False)
                    obj.user = curruser #Save the note note under that user
                    obj.save() #save the new object
                    
                except Exception, e:
                    print("errors" + str(e))
                response = {'status': 1, 'message':'ok'}
                return HttpResponse(json.dumps(response, cls=DjangoJSONEncoder)) #return to ajax as success with all the new records.
            
        return super(MyView, self).get(request)
    

class NoteDelete(DeleteView):
    model = Note
    success_url = '/list/'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NoteDelete, self).dispatch(*args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(NoteDelete, self).get_context_data(**kwargs)
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context
    
class Landing(TemplateView):
    template_name = "notes/landing.html"
    

notes/templates/notes/base.html
{# Load the tag library #}
{% load bootstrap3 %}

<head>
  <title>
    {%block title%}
    {%endblock%}
  </title>
</head>
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script type="text/css">
.mynavbar {
    display:block;
    margin:0px;
    padding:0px;
    height:50px;
}

</script>
<script type="text/javascript">
    $(document).ready(function() {
        jQuery.ajaxSettings.traditional = true; //Important 
        
        /*Important functions to enable CSRF token as Django requires it*/
        function getCookie(name) {
            var cookieValue = null;
            var i = 0;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (i; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
    
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        /*end CSRF token */
    
        /*Setting the format of the datepicker and datetimepicker*/
        $('.dateinput').datepicker({
            format: "yyyy/mm/dd"
        });
        $('.datetimeinput').datetimepicker({
            format: "YYYY-MM-DD HH:mm"
        });
    
       
        $('.createfolder').click(function(e) {
            
            formid = $(this).parent().attr("id"); //find the formid of the button pressed via parent 
            
            $.ajax({
                type: "POST",
                url: "/add/",
                dataType: "json",
                data: {
                    "title": $("#" + formid + " #id_title").val(),
                    "color": $("#" + formid + " #id_color").val(),
                    "fontcolor": $("#" + formid + " #id_fontcolor").val(),
                    "form": $("#" + formid).serialize(),
    
                },
                success: function(data, status) {
                    //Populate the dropdown list with all the folders returned in json
                    var $el = $("#id_folder");
                    $el.empty(); // remove old options
                    $el.append($("<option></option>").attr("value", "").text("---------"));
                    $.each(data, function(key, value) {
                        $el.append($("<option></option>").attr("value", value.id).text(value.title));
                    });
                },
                crossDomain: false, // obviates need for sameOrigin test
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
        
        $('.createtag').click(function(e) {
            formid = $(this).parent().attr("id"); //find the formid of the button pressed via parent 
            
            $.ajax({
                type: "POST",
                url: "/add/",
                dataType: "json",
                data: {
                    "title": $("#" + formid + " #id_title").val(),
                    "color": $("#" + formid + " #id_color").val(),
                    "fontcolor": $("#" + formid + " #id_fontcolor").val(),
                    "form": $("#" + formid).serialize(),
    
                },
                success: function(data, status) {
                    //Populate the dropdown list with all the folders returned in json
                    var $el = $("#id_tag");
                    $el.empty(); // remove old options
                    $.each(data, function(key, value) {
                        $el.append($("<option></option>").attr("value", value.id).text(value.title));
                    });
                },
                crossDomain: false, // obviates need for sameOrigin test
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
        
        $('.btn.createnote').click(function(e) {
            
            formid = $(this).parent().attr("id"); //find the formid of the button pressed via parent 
    
            $.ajax({
                type: "POST",
                url: "/add/",
                dataType: "json",
                data: {
                     "title": $("#" + formid + " #id_title").val(),
                     "done": $("#" + formid + " #id_done").prop("checked"),
                     "content": $("#" + formid + " #id_content").val(),
                     "join_date": $("#" + formid + " #id_join_date").val(),
                     "color": $("#" + formid + " #id_color").val(),
                     "fontcolor": $("#" + formid + " #id_fontcolor").val(),
                     "folder": $("#" + formid + " #id_folder").val(),
                     "tag": $("#" + formid + " #id_tag").val(),
                     "Sponsor": $("#" + formid + " #id_Sponsor").val(),
                     "Games": $("#" + formid + " #id_Games").val(),
                     "form": $("#" + formid).serialize(),
    
                },
                success: function(data) {
                    if (data.status == 1){
                        //alert(data.message)
                        //http://stackoverflow.com/questions/503093/how-can-i-make-a-redirect-page-using-jquery
                        window.location.replace("/list") //to redirect to another page
                    }
                },
                crossDomain: false, // obviates need for sameOrigin test
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
        
        /* To reset the modal input fields when modal is closed.*/
        $('#myModal').on('hidden.bs.modal', function(){
            $(this).find('form')[0].reset();
        });
        /* To reset the modal input fields when modal is closed.*/
        $('#myModal2').on('hidden.bs.modal', function(){
            $(this).find('form')[0].reset();
        });
    });
</script>
</head>
<body>
<div class="mynavbar">
        <ul class="nav nav-tabs navbar-right">
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">
                  {%if user.is_authenticated%}
                      <img src="/media/{{curruser.picture}}" height="30px" %} />
                      Hi {{user.username}}!
                  {%else%}
                      Login here!
                  {%endif%}
                  
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  {%if user.is_authenticated%}
                      <li><a href="/accounts/logout">Logout</a></li>
                      <li><a href="/add">Add a Player</a></li>
                      <li><a href="/list">View all Player</a></li>
                  {%else%}
                      <li><a href="/accounts/login">Login</a></li>
                  {%endif%}
                
                      
                </ul>
              </li>
            </ul>
        <!--</div>-->
    <!--</div>-->
</div>
{%block content%}

{%endblock%}
</body>

notes/templates/notes/folder_list.html
{%extends 'notes/base.html'%}
{%load staticfiles%}

{%block content%}
    <h3>Folder</h3>
    <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
    {% if object_list  %}
        <ul>
        {% for folder in object_list  %}
            <li>{{folder.title}}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No folders are available.</p>
    {% endif %}
{%endblock%}

notes/templates/notes/landing.html
{%extends 'notes/base.html'%}

{%block content%}
    
{%endblock%}

notes/templates/notes/note_confirm_delete.html
{%extends 'notes/base.html'%}
{%load staticfiles%}

{%block content%}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{%endblock%}

notes/templates/notes/note_detail.html
{%extends 'notes/base.html'%}
{%block title%}
    Note - {{object.title}}
{%endblock%}
{%block content%}
<style>
.container {
    background-color:black;
    color:white;
    width:100%;
    height:100%;
} 
</style>
    <div class="container">
        <h1>Player Name:</h1> 
        <p>{{object.title}}</p>
        <h1>Description:</h1>
        <p>{{object.content}}</p>
        <h1>Latest Achievement:</h1>
        <p>{{object.Achievements}}</p>
        <h1>Sponsored by:</h1>
        <p>{{object.Sponsor}}</p>
        <h2>Games Played:</h2>
        <ul>
        {%for t in object.Games.all%}
                    <li>{{t.title}}</li>
                {%endfor%}
                </ul>
    </div>
{%endblock%}

notes/templates/notes/note_form.html
{%extends 'notes/base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <!--distinguish between update or create view-->
            <!--http://stackoverflow.com/questions/18806703/within-a-template-distinguish-between-create-and-update-form-->
            {%if object%}
                <h1>Update {{object.title}}</h1>
            {%else%}
                <h1>Add a Player</h1>
            {%endif%}
            {% crispy form %}
        </div>
    </div>
</div>
{%endblock%}

notes/templates/notes/note_hybrid.html
{%extends 'notes/base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div class="mymessage">
   {{ createnote_form.errors }}
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Add a Player</h3>
            {%if createnote_form %}
                {%crispy createnote_form%}
            {%endif%}
            
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add a Sponsor</h4>
                  </div>
                  <div class="modal-body">
                    <!--MODAL ADD FOLDER-->
                    {%if createSponsor_form%} {% crispy createSponsor_form %} {%endif%}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add a Game</h4>
                  </div>
                  <div class="modal-body">
                    {%if createGames_form%} {% crispy createGames_form %} {%endif%}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>

        </div>
    </div>
</div>
{%endblock%}

notes/templates/notes/note_list.html
{%extends 'notes/base.html'%}
{%load staticfiles%}

{%block content%}
<div class="container">
    <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
    <h2>FaZebook: Home of the MLG</h2>

    {% if object_list  %}
        {% for note in object_list  %}
            <a href={%url 'note_update' note.id %}>
                <div class="shrek">
                
                    <br>
                    <u>{{note.title}}</u>
                    <br>
                    {{note.content}}
                </div>
            </a>
        {% endfor %}
    {% else %}
        <p>No Players are registered yet.</p>
    {% endif %}
</div>
<h1> Brought to you by:</h1>
<img src = "https://silversporknews.files.wordpress.com/2015/02/doritos-nacho-cheese.gif">
<img src = "http://img3.wikia.nocookie.net/__cb20140727190433/mountaindew/images/9/91/Mdbottle_zps52ac0b35.png">
{%endblock%}

notes/templates/notes/tag_list.html
{%extends 'notes/base.html'%}
{%load staticfiles%}

{%block content%}
    <h3>Tags</h3>
    <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
    {% if object_list  %}
        <ul>
        {% for tag in object_list  %}
            <li>{{tag.title}}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No tag are available.</p>
    {% endif %}
{%endblock%}